name: Build and Release Book

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: >-
            latexmk xetex fontspec titlesec setspace microtype parskip xcolor tocloft geometry kvoptions ltxcmds kvsetkeys mdframed zref needspace hyperref fancyhdr polyglossia hyphen-russian graphics oberdiek xdvipdfmx epigraph nextpage csquotes bookmark quoting

      - name: Install Pandoc
        uses: pandoc/actions/setup@v1
        with:
          version: '3.5'

      - name: Install system fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-roboto
          sudo apt-get install -y fonts-noto-core fonts-dejavu texlive-lang-cyrillic
          sudo fc-cache -f -v

      - name: Compile LaTeX to PDF with XeLaTeX
        run: |
          export PATH="/home/runner/work/_temp/setup-texlive-action/2024/bin/x86_64-linux:$PATH"
          latexmk -pdf -xelatex -interaction=nonstopmode -f book_what_is_your_number.tex
        
      - name: Generate HTML with Pandoc
        run: |
          pandoc -s book_what_is_your_number.tex -o book_what_is_your_number-${{ github.ref_name }}.html

      - name: Generate EPUB with Pandoc
        run: |
          pandoc -s book_what_is_your_number.tex -o book_what_is_your_number-${{ github.ref_name }}.epub

      - name: Generate FB2 with Pandoc
        run: |
          pandoc -s book_what_is_your_number.tex -o book_what_is_your_number-${{ github.ref_name }}.fb2

      - name: Install Calibre
        run: |
          sudo apt-get update
          sudo apt-get install -y calibre

      - name: Convert EPUB to MOBI
        run: |
          ebook-convert book_what_is_your_number-${{ github.ref_name }}.epub book_what_is_your_number-${{ github.ref_name }}.mobi

      - name: Create and Upload Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            book_what_is_your_number.pdf
            book_what_is_your_number-${{ github.ref_name }}.html
            book_what_is_your_number-${{ github.ref_name }}.epub
            book_what_is_your_number-${{ github.ref_name }}.fb2
            book_what_is_your_number-${{ github.ref_name }}.mobi